import { notFound } from "next/navigation";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import {
  getAllCategories,
  getCategoryById,
  getManufacturerBySlug,
  getProductBySlug,
  getProductsByCategoryId,
  getRelatedProducts,
} from "@/lib/data";
import { ProductGallery } from "@/components/product/ProductGallery";
import { ProductSpecs } from "@/components/product/ProductSpecs";
import { ProductDataTable } from "@/components/product/ProductDataTable";
import { RelatedProducts } from "@/components/product/RelatedProducts";
import { AddToCartActions } from "@/components/product/AddToCartActions";
import { VacuumProductDetail } from "@/components/product/VacuumProductDetail";
import { VariantProductDetail } from "@/components/product/VariantProductDetail";
import { JsonLd } from "@/components/seo/JsonLd";
import {
  buildAlternates,
  buildBreadcrumbJsonLd,
  buildProductJsonLd,
  localePath,
} from "@/lib/seo";
import type { Metadata } from "next";
import type { Locale } from "@/i18n/routing";
import { routing } from "@/i18n/routing";

interface ProductPageProps {
  params: Promise<{ locale: Locale; category: string; product: string }>;
}

export function generateStaticParams() {
  const categories = getAllCategories();
  const params: { locale: Locale; category: string; product: string }[] = [];
  for (const locale of routing.locales) {
    for (const cat of categories) {
      const products = getProductsByCategoryId(cat.id);
      for (const p of products) {
        params.push({
          locale: locale as Locale,
          category: cat.id,
          product: p.slug,
        });
      }
    }
  }
  return params;
}

export async function generateMetadata({
  params,
}: ProductPageProps): Promise<Metadata> {
  const { locale, category, product: productSlug } = await params;
  const product = getProductBySlug(category, productSlug, locale);
  if (!product) return {};

  // Build a meta description that is long enough for Google (~150-160 chars)
  // but doesn't get truncated mid-word. Prefer shortDescription when it's
  // long enough; otherwise pull from full description.
  const raw = (product.shortDescription || "").trim();
  const desc =
    raw.length >= 80
      ? raw
      : ((product.description || "").slice(0, 280).trim() || raw);

  const keywords = (product.searchKeywords ?? []).filter(Boolean);

  // OG image is auto-generated by opengraph-image.tsx — no manual URL needed.
  return {
    title: product.name,
    description: desc,
    keywords: keywords.length > 0 ? keywords : undefined,
    alternates: buildAlternates(locale, `/catalog/${category}/${product.slug}`),
    openGraph: {
      title: product.name,
      description: desc,
      type: "article",
    },
  };
}

export default async function ProductPage({ params }: ProductPageProps) {
  const { locale, category, product: productSlug } = await params;
  setRequestLocale(locale);
  const product = getProductBySlug(category, productSlug, locale);
  if (!product) notFound();

  const cat = getCategoryById(category, locale);
  const related = getRelatedProducts(product, 4, locale);
  const sku = product.catalogNumber || `P-${product.id.slice(-6).toUpperCase()}`;
  const manufacturer = product.manufacturer
    ? getManufacturerBySlug(product.manufacturer, locale)
    : undefined;
  const tNav = await getTranslations("nav");
  const tProd = await getTranslations("productPage");
  const tCommon = await getTranslations("common");

  const productJsonLd = buildProductJsonLd({
    product,
    category: cat,
    manufacturer,
    locale,
  });

  const breadcrumbJsonLd = buildBreadcrumbJsonLd([
    { name: tNav("home"), url: localePath(locale, "/") },
    { name: tNav("catalog"), url: localePath(locale, "/catalog") },
    ...(cat
      ? [{ name: cat.name, url: localePath(locale, `/catalog/${cat.id}`) }]
      : []),
    {
      name: product.name,
      url: localePath(locale, `/catalog/${category}/${product.slug}`),
    },
  ]);

  return (
    <>
      <JsonLd data={[productJsonLd, breadcrumbJsonLd]} />
      <section className="bg-paper-100 pt-6 md:pt-7 pb-6 md:pb-7 border-b border-paper-200">
        <div className="max-w-[1320px] mx-auto px-4 md:px-10 lg:px-14">
          <nav className="flex items-center gap-2 text-[12px] text-ink-500 flex-wrap">
            <Link href="/" className="hover:text-green-700">{tNav("home")}</Link>
            <span>/</span>
            <Link href="/catalog" className="hover:text-green-700">{tNav("catalog")}</Link>
            {cat && (
              <>
                <span>/</span>
                <Link href={`/catalog/${cat.id}`} className="hover:text-green-700">
                  {cat.name}
                </Link>
              </>
            )}
            <span>/</span>
            <span className="text-ink-900 font-medium truncate">{product.name}</span>
          </nav>
        </div>
      </section>

      <section className="bg-white pb-16">
        <div className="max-w-[1320px] mx-auto px-4 md:px-10 lg:px-14">
          {category === "vacuum-systems" ||
          (category === "consumables" &&
            (product.variants?.length ?? 0) > 0) ? (
            <div className="mt-6 mb-14">
              {category === "vacuum-systems" ? (
                <VacuumProductDetail family={product} />
              ) : (
                <VariantProductDetail family={product} />
              )}
              {(cat || product.tags.length > 0 || manufacturer) && (
                <div className="flex flex-wrap gap-2 mt-6">
                  {cat && (
                    <Link
                      href={`/catalog/${cat.id}`}
                      className="pill pill-green hover:bg-green-200 transition-colors"
                    >
                      {cat.name}
                    </Link>
                  )}
                  {manufacturer && (
                    <Link
                      href={`/manufacturers/${manufacturer.slug}`}
                      className="pill hover:bg-paper-200 transition-colors"
                    >
                      {manufacturer.name}
                    </Link>
                  )}
                  {product.tags.map((tag) => (
                    <span key={tag} className="pill">
                      {tag}
                    </span>
                  ))}
                </div>
              )}
            </div>
          ) : (
            <>
              <div className="grid lg:grid-cols-[1.1fr_1fr] gap-10 lg:gap-12 mb-14 mt-6">
                <ProductGallery images={product.images} name={product.name} />

                <div className="flex flex-col gap-5">
                  <div className="flex flex-wrap items-center gap-2">
                    <span
                      className={`inline-flex items-center text-[11px] font-bold tracking-[0.08em] uppercase px-2.5 py-1 rounded-full ${
                        product.inStock ? "bg-green-500 text-white" : "bg-ink-700 text-white"
                      }`}
                    >
                      {product.inStock ? tProd("inStock") : tProd("byOrder")}
                    </span>
                    <span className="font-mono text-[12px] text-ink-500">{tProd("sku")} {sku}</span>
                    {manufacturer && (
                      <Link
                        href={`/manufacturers/${manufacturer.slug}`}
                        className="text-[12px] text-ink-500 hover:text-green-700 transition-colors"
                      >
                        · {manufacturer.name}
                      </Link>
                    )}
                  </div>

                  <h1 className="display-heading text-ink-900 text-3xl md:text-4xl lg:text-[42px]">
                    {product.name}
                  </h1>

                  <p className="text-[15px] leading-relaxed text-ink-700">
                    {product.description || product.shortDescription}
                  </p>

                  {(cat || product.tags.length > 0) && (
                    <div className="flex flex-wrap gap-2">
                      {cat && (
                        <Link
                          href={`/catalog/${cat.id}`}
                          className="pill pill-green hover:bg-green-200 transition-colors"
                        >
                          {cat.name}
                        </Link>
                      )}
                      {product.tags.map((tag) => (
                        <span key={tag} className="pill">
                          {tag}
                        </span>
                      ))}
                    </div>
                  )}

                  <AddToCartActions product={product} />

                  <a
                    href={`tel:${tCommon("phone").replace(/\s/g, "")}`}
                    className="btn btn-ghost"
                  >
                    <svg viewBox="0 0 24 24" className="icon w-4 h-4">
                      <path d="M5 4h4l2 5-3 2a11 11 0 0 0 5 5l2-3 5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2z" />
                    </svg>
                    {tCommon("phone")}
                  </a>
                </div>
              </div>

              <div className="grid grid-cols-1 gap-6">
                <ProductSpecs specs={product.specs} />
                {product.dataTable && <ProductDataTable table={product.dataTable} />}
              </div>
            </>
          )}

          <RelatedProducts products={related} />
        </div>
      </section>
    </>
  );
}
